import fs from "node:fs";
import path from "node:path";
import katex from "katex";
import { createDeck } from "../presentations/areal/deck.mjs";
import { icons } from "lucide/dist/esm/lucide.js";
import { presenterIcons, lucideLicense } from "./icons.mjs";
const root = path.resolve(import.meta.dirname, "..");
const source = path.join(root, "presentations/areal");
const buildDir = path.join(root, "work/build");
const dir = path.join(buildDir, "presentations/areal");
fs.rmSync(buildDir, { recursive: true, force: true });
fs.mkdirSync(dir, { recursive: true });
fs.cpSync(path.join(source, "assets"), path.join(dir, "assets"), {
  recursive: true,
});
const enc = (s) =>
  String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
const asset = (p) => p;
const math = (t, cls = "") =>
  `<div class="math ${cls}" data-tex="${enc(t)}">${katex.renderToString(t, { displayMode: true, throwOnError: true, output: "htmlAndMathml" })}</div>`;
const link = (u, t) => `<a href="${u}" target="_blank" rel="noopener">${t}</a>`;
const { slides, SRC } = createDeck({
  logo: "assets/brand/areal.png",
  antBlue: "assets/brand/ant-blue.png",
  antWhite: "assets/brand/ant-white.png",
  asset,
  math,
  enc,
  link,
});
const notes = Object.fromEntries(
  Object.entries(slides).map(([n, s]) => [
    n,
    {
      title: s.title,
      notes: s.notes,
      refs: s.refs.map((id) => SRC[id]),
      figures: s.figures || [],
    },
  ]),
);
const katexDist = new URL(".", import.meta.resolve("katex"));
fs.cpSync(new URL("fonts", katexDist), path.join(dir, "assets/fonts"), {
  recursive: true,
});
const katexLicense = fs.readFileSync(
  new URL("../LICENSE", import.meta.resolve("katex")),
  "utf8",
);
let css =
  "/* KaTeX MIT License\n" +
  katexLicense +
  "\n*/\n" +
  fs
    .readFileSync(new URL("katex.min.css", katexDist), "utf8")
    .replaceAll("url(fonts/", "url(assets/fonts/");
for (const name of ["foundation", "slides", "training"])
  css +=
    "\n" + fs.readFileSync(path.join(source, `styles/${name}.css`), "utf8");
css = css
  .replace("__BG__", "assets/brand/slide-background.png")
  .replace("__SECTION_BG__", "assets/brand/section-background.png");
fs.writeFileSync(
  path.join(dir, "content.html"),
  Object.values(slides)
    .map((s) => s.html)
    .join("\n"),
);
fs.writeFileSync(path.join(dir, "styles.css"), css);
fs.writeFileSync(path.join(dir, "notes.json"), JSON.stringify(notes, null, 2));
fs.writeFileSync(
  path.join(dir, "metadata.json"),
  JSON.stringify(
    {
      ...JSON.parse(
        fs.readFileSync(path.join(source, "metadata.json"), "utf8"),
      ),
      slideCount: Object.keys(slides).length,
    },
    null,
    2,
  ),
);
const names = [
  "Library",
  "Type",
  "RectangleHorizontal",
  "SquareRoundCorner",
  "Circle",
  "Triangle",
  "Diamond",
  "Hexagon",
  "Star",
  "ArrowRight",
  "Minus",
  "MessageSquare",
  "Square",
  "ArrowUp",
  "ArrowDown",
  "AlignLeft",
  "AlignCenter",
  "AlignRight",
  "Magnet",
  "Sigma",
  "Sun",
  "Moon",
  "Monitor",
  "Bold",
  "Italic",
  "Underline",
  "Strikethrough",
  "ChevronUp",
  "Pipette",
  "Ban",
  "CornerUpLeft",
  "Fingerprint",
  "KeyRound",
  "Shield",
  "Globe",
  "ChevronDown",
  "ArrowUpRight",
  "Plus",
  "Search",
  "LockKeyhole",
  "Link",
  "Settings2",
  "LogOut",
  "Presentation",
  "Pencil",
  "Upload",
  "Copy",
  "Trash2",
  "RotateCcw",
  "FolderOpen",
  "ArrowLeft",
  "ChevronRight",
  "X",
  "Check",
  "Clock3",
  "Image",
  "FileCode2",
  "Save",
  "Eye",
  "Download",
  "CircleAlert",
  "LoaderCircle",
  "ShieldCheck",
  "ExternalLink",
  "CheckCheck",
];
const selected = { ...presenterIcons };
for (const name of names) {
  const key = name[0].toLowerCase() + name.slice(1);
  selected[key] = {
    name: name
      .replace(/[a-z0-9][A-Z]/g, (s) => s[0] + "-" + s[1])
      .toLowerCase(),
    body: icons[name]
      .map(
        ([tag, attrs]) =>
          `<${tag} ${Object.entries(attrs)
            .map(([k, v]) => `${k}="${enc(v)}"`)
            .join(" ")}/>`,
      )
      .join(""),
  };
}
fs.writeFileSync(
  path.join(buildDir, "icons.js"),
  `/* Lucide icons.\n${lucideLicense}\n*/\n// Generated by scripts/build.mjs.\nexport const icons=${JSON.stringify(selected)};\nexport const icon=(name,cls='')=>{const i=icons[name];return \`<svg class="lucide \${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${i.body}</svg>\`;};\n`,
);
console.log("Built content package: areal (27 slides), shared Lucide icons.");

fs.cpSync(
  new URL(".", import.meta.resolve("@simplewebauthn/browser")),
  path.join(buildDir, "webauthn"),
  { recursive: true },
);
fs.copyFileSync(
  new URL("../LICENSE.md", import.meta.resolve("@simplewebauthn/browser")),
  path.join(buildDir, "webauthn/LICENSE"),
);

const katexTarget = path.join(buildDir, "katex");
fs.mkdirSync(katexTarget, { recursive: true });
for (const file of ["katex.mjs", "katex.min.css"])
  fs.copyFileSync(new URL(file, katexDist), path.join(katexTarget, file));
fs.cpSync(new URL("fonts", katexDist), path.join(katexTarget, "fonts"), {
  recursive: true,
});
